//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everpass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passwords
    {
        public int PasswordID { get; set; }
        public string WebsiteName { get; set; }
        public string UserPassword { get; set; }
        public int SecurityLevel { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
